### ISSUE TITLE
Calling refreshComments throws a failed assertion error

### ISSUE THREAD

**Issue by TheNightmanCodeth** [draw-dev/DRAW#100]
I have this method:

>Future<CommentForest> initComments() async {
  CommentForest comments = await submission.refreshComments();  
  return comments;   
}

For some reason when I use the CommentForest returned by it I'm always receiving this error:

> 'package:draw/src/models/submission_impl.dart': Failed assertion: line 38 pos 10: '!s._commentsById.containsKey(c.fullname)': is not true.

I remove the assert on line 38 and the problem is gone. Anyone have any ideas why this might be happening?

**Comment by bkonyi** [comment]
@TheNightmanCodeth, do you happen to have the exact submission this happened for? Also, when you say you use the `CommentForest` what do you mean by that exactly? How are you interacting with the `CommentForest`?

**Comment by TheNightmanCodeth** [comment]
I don't have the exact submission, but for some reason I haven't run into this problem since it happened. I'll update if I run into it again.

**Comment by bkonyi** [comment]
Sounds good to me. I'll close this for now, but if you see it again please feel free to reopen.
