### ISSUE TITLE
i.redditmedia.com links need to unescape &amp;

### ISSUE THREAD

**Issue by TheNightmanCodeth** [draw-dev/DRAW#104]
For example, this link:
>https://i.redditmedia.com/LO9bMLl0OFEAQ6XJPl6yXg1lv6Rdv_iHWIYw_Y8rgVg.png?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=dec028b663cc791538042d7df6e7c0b1

which was returned by a `submission.preview`, will return a `403` error. Remove all of the `amp;` and we get:

>https://i.redditmedia.com/LO9bMLl0OFEAQ6XJPl6yXg1lv6Rdv_iHWIYw_Y8rgVg.png?fit=crop&crop=faces%2Centropy&arh=2&w=1080&s=dec028b663cc791538042d7df6e7c0b1

which works properly. 

For now I'm calling `.replaceAll("amp;", "")` on my urls but I see no reason why this can't be done in the actual `SubmissionPreview` implementation

**Comment by bkonyi** [comment]
This is fixed in the master branch and will be part of the next release (probably sometime today).

**Comment by bkonyi** [comment]
Fixed in 0.4.2
