### ISSUE TITLE
Quiver 2.0 Incompatibility.

### ISSUE THREAD

**Issue by LucasCLuk** [draw-dev/DRAW#106]
The current version of DRAW `0.4.1` is not compatible with quiver 2.0

`Because every version of flutter_test from sdk depends on quiver 2.0.0+1 and draw >=0.3.0 depends on quiver >=0.26.2 <1.0.0, flutter_test from sdk is incompatible with draw >=0.3.0.`

**Comment by bkonyi** [comment]
I'll bump the version for quiver in the next release which should be out today or tomorrow. In the meantime, you can probably get around the issue for now by adding a fixed version number for quiver under the `dependency_overrides` section of your `pubspec.yaml`.

**Comment by LucasCLuk** [comment]
Alright. Thanks
