### ISSUE TITLE
DRAWAuthenticationError: Status Code: unauthorized_client Reason: null

### ISSUE THREAD

**Issue by 1nv1n** [draw-dev/DRAW#128]
I'm running into `DRAWAuthenticationError: Status Code: unauthorized_client Reason: null`.

Full log:
```
E/flutter ( 2174): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2174): DRAWAuthenticationError: Status Code: unauthorized_client Reason: null
E/flutter ( 2174): #0      Reddit.createScriptInstance (package:draw/src/reddit.dart:202:25)
E/flutter ( 2174): <asynchronous suspension>
E/flutter ( 2174): #1      main (package:sreddit/main.dart:22:32)
E/flutter ( 2174): <asynchronous suspension>
E/flutter ( 2174): #2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 2174): #3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

I'm using this (or trying to), the way described:
```
Reddit reddit = await Reddit.createScriptInstance(
    clientId: "ID_HERE",
    clientSecret: "SECRET_HERE",
    userAgent: "SReddit",
    username: "MY_USERID",
    password: "MY_PASS",
  );

  Redditor currentUser = await reddit.user.me();
  print("Name: ${currentUser.displayName}");
```

What am I doing incorrectly here?

PubSpec details:
`draw: ^0.4.6`
`dart sdk: ">=2.1.0-dev.9.4.flutter-f9ebf21297 <3.0.0"`

**Comment by bkonyi** [comment]
Hi @1nv1n, thanks for the report.

Assuming your credentials are correct, have you tried changing your `userAgent`? I'll investigate further to see if I can reproduce myself.

**Comment by kevinespaldon** [comment]
I've encountered this earlier, the problem was that I was putting the wrong credentials.

**Comment by 1nv1n** [comment]
Hey @bkonyi & @kevinespaldon , thanks for responding. I've just double-checked that I'm using the correct username & password. Copy-pasted the same & was able to log into Reddit in a browser.

I tried updating the `userAgent` as well; no luck. Same stacktrace as well. Is there anything else that I could try?

**Comment by ssxx112** [comment]
Hey @1nv1n sorry to bump an old thread but i am running in to the same issue, have you discovered a fix ?

**Comment by kevinespaldon** [comment]
@ssxx112 Credentials are good?

**Comment by 1nv1n** [comment]
No, I have not yet found a fix. I also have not looked into it since Feb.; I will try to check again (doubt it'll be different - but Dart & Flutter have had updates since the last time I checked (low chance of that resolving it)); but I'll post an update to this comment with the results.

**Comment by bkonyi** [comment]
If you're still having issues, could you post a simple reproduction case that I could try out? Sorry I haven't been able to look into this more myself, I've been pretty swamped lately. If it's a relatively quick fix I can get it done this week or guide you down the right path :)

**Comment by ssxx112** [comment]
I found to fix this problem was to register the app on the reddit website as a script instead of an installed app and everything worked out great.

**Comment by StefanLobbenmeier** [comment]
Glad you were able to resolve your issues :) just out of curiosity, with the „installed app“ type you don’t get a client secret (right?), so what parameter did you chose there?
