### ISSUE TITLE
Getting an exception on createScriptInstance

### ISSUE THREAD

**Issue by kevinespaldon** [draw-dev/DRAW#129]
I'm getting an error when calling createScriptInstance

Here's the exception:

`
   [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'Future<void>' is not a subtype of type 'Redditor'
   #0      main 
   package:sirena/main.dart:35
   #1      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:170:23)
   #2      _rootRun (dart:async/zone.dart:1124:13)
   #3      _CustomZone.run (dart:async/zone.dart:1021:19)   
   #4      _runZoned (dart:async/zone.dart:1516:10)   
   #5      runZoned (dart:async/zone.dart:1500:12)   
   #6      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:169:5)   
   #7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)   
   #8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
`

On breakpoint investigation, it continues to this line

`      
    // Retrieve information for the currently authenticated user
    Redditor currentUser = await reddit.user.me();
`

and successfully filling `currentUser` with the object and printing the display name with

`print("My name is ${currentUser.displayName}");`

This implies that the credentials are correct so let's tick that box already.

Thanks! <3

**Comment by bkonyi** [comment]
Thanks for filing the issue @kevinespaldon!

Would you mind showing me what's actually at line 35 in your main.dart? It's hard to tell what's happening since the exception isn't coming from within the package.

**Comment by kevinespaldon** [comment]
I've put it in a gist for you. Line 35 is actually runApp

**Comment by kevinespaldon** [comment]
When I remove the parameter of `redditor` from my stateful widget, the exception isn't fired anymore so I might be doing something wrong. Sorry about opening an issue, it's on me. 😬Just exploring flutter and creating a reddit app seems interesting so I stumbled upon your package and started exploring.

Now that I have you, can you suggest a way to pass the current Redditor object into inherited widgets? You know, to pass how posts in one scaffold, my inbox in another scaffold etc.

**Comment by bkonyi** [comment]
@kevinespaldon, it looks like you're doing something wrong for the `runApp` call. `runApp` expects a `Widget` input and you're passing in a `RedditorRef` (see [here](https://docs.flutter.io/flutter/widgets/runApp.html) for `runApp` documentation).

In all honesty, I'm not sure how to pass data into inherited widgets. I may be a contributor to the Flutter project, but I haven't really used it much myself yet. You'll probably have some luck looking at tutorials on www.flutter.dev, the Flutter Gitter forum, Medium, or StackOverflow.
