### ISSUE TITLE
Submission needs an entry to access data['media']

### ISSUE THREAD

**Issue by StefanLobbenmeier** [draw-dev/DRAW#131]
Basically before that https://github.com/draw-dev/DRAW/blob/79bbb9d5272bfef6a581abda174d82bb2d7e5b20/lib/src/models/submission_impl.dart#L204. Is there any reason some of the data fields (e.g. media) do not have getters? We should also think about which type it would have, since the content of that field can vary. Examples:

> From [https://v.redd.it/gyh95hiqc0b11](https://v.redd.it/gyh95hiqc0b11) - media: {reddit_video: {fallback_url: https://v.redd.it/gyh95hiqc0b11/DASH_9_6_M?source=fallback, height: 1080, width: 608, scrubber_media_url: https://v.redd.it/gyh95hiqc0b11/DASH_600_K, dash_url: https://v.redd.it/gyh95hiqc0b11/DASHPlaylist.mpd, duration: 14, hls_url: https://v.redd.it/gyh95hiqc0b11/HLSPlaylist.m3u8, is_gif: true, transcoding_status: completed}}

> From [Our Unit Test](https://github.com/draw-dev/DRAW/blob/master/test/submission/lib_submission_properties.json) - 
```
"media": {
                  "type": "youtube.com",
                  "oembed": {
                    "provider_url": "https://www.youtube.com/",
                    "title": "DRAW: Using Dart to Moderate Reddit Comments (DartConf 2018)",
                    "type": "video",
                    "html": "&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/VqNU_CYVaXg?feature=oembed&amp;enablejsapi=1&amp;enablejsapi=1\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen&gt;&lt;/iframe&gt;",
                    "thumbnail_width": 480,
                    "height": 338,
                    "width": 600,
                    "version": "1.0",
                    "author_name": "Google Developers",
                    "provider_name": "YouTube",
                    "thumbnail_url": "https://i.ytimg.com/vi/VqNU_CYVaXg/hqdefault.jpg",
                    "thumbnail_height": 360,
                    "author_url": "https://www.youtube.com/user/GoogleDevelopers"
                  }
```

**Comment by StefanLobbenmeier** [comment]
This is probably linked to this: https://github.com/praw-dev/praw/issues/726

**Comment by bkonyi** [comment]
Thanks for the issue @StefanLobbenmeier!

The reason why there's not getters for each property is that Reddit doesn't have a complete listing of the possible properties and the API doesn't consistently return the same properties for each request. The getters that are there are the ones which I've seen consistently, but they're by no means a complete set.

Do you happen to know what the different types of content can be? If so, I'm happy to accept pull requests or design input!

**Comment by StefanLobbenmeier** [comment]
Sry for the late response. I will look into this, but I am currently concentrating on more basic parts of the API, but I expect I will investigate this further in a few month.

**Comment by StefanLobbenmeier** [comment]
I hope you dont mind if I use this issue to document my findings - I want to gather as many examples of media before thinking about a good design.

**Comment by StefanLobbenmeier** [comment]
gyfcat
media_embed: {content: &lt;iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Fconstantdecimalkarakul&amp;url=https%3A%2F%2Fgfycat.com%2Fconstantdecimalkarakul&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FConstantDecimalKarakul-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat" width="600" height="338" scrolling="no" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="true"&gt;&lt;/iframe&gt;, width: 600, scrolling: false, height: 338}
secure_media: {type: gfycat.com, oembed: {provider_url: https://gfycat.com, description: Watch xD GIF by @tomyhy on Gfycat. Discover more related GIFs on Gfycat, title: xD, thumbnail_width: 444, height: 338, width: 600, html: &lt;iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Fconstantdecimalkarakul&amp;url=https%3A%2F%2Fgfycat.com%2Fconstantdecimalkarakul&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FConstantDecimalKarakul-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat" width="600" height="338" scrolling="no" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="true"&gt;&lt;/iframe&gt;, version: 1.0, provider_name: Gfycat, thumbnail_url: https://thumbs.gfycat.com/ConstantDecimalKarakul-size_restricted.gif, type: video, thumbnail_height: 250}}
is_reddit_media_domain: false
secure_media_embed: {content: &lt;iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Fconstantdecimalkarakul&amp;url=https%3A%2F%2Fgfycat.com%2Fconstantdecimalkarakul&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FConstantDecimalKarakul-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat" width="600" height="338" scrolling="no" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="true"&gt;&lt;/iframe&gt;, width: 600, scrolling: false, media_domain_url: https://www.redditmedia.com/mediaembed/7s6y7w, height: 338}
media_only: false
media: {type: gfycat.com, oembed: {provider_url: https://gfycat.com, description: Watch xD GIF by @tomyhy on Gfycat. Discover more related GIFs on Gfycat, title: xD, thumbnail_width: 444, height: 338, width: 600, html: &lt;iframe class="embedly-embed" src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fgfycat.com%2Fifr%2Fconstantdecimalkarakul&amp;url=https%3A%2F%2Fgfycat.com%2Fconstantdecimalkarakul&amp;image=https%3A%2F%2Fthumbs.gfycat.com%2FConstantDecimalKarakul-size_restricted.gif&amp;key=ed8fa8699ce04833838e66ce79ba05f1&amp;type=text%2Fhtml&amp;schema=gfycat" width="600" height="338" scrolling="no" frameborder="0" allow="autoplay; fullscreen" allowfullscreen="true"&gt;&lt;/iframe&gt;, version: 1.0, provider_name: Gfycat, thumbnail_url: https://thumbs.gfycat.com/ConstantDecimalKarakul-size_restricted.gif, type: video, thumbnail_height: 250}}

**Comment by StefanLobbenmeier** [comment]
imgur (only link information):

media_embed: {}
secure_media: null
is_reddit_media_domain: false
secure_media_embed: {}
media_only: false
url: https://i.imgur.com/4a3Ch82.gifv
media: null

**Comment by StefanLobbenmeier** [comment]
Reddit video

```
media_embed: {}
secure_media: {reddit_video: {fallback_url: https://v.redd.it/yaydjqjx91o21/DASH_1080?source=fallback, height: 1080, width: 540, scrubber_media_url: https://v.redd.it/yaydjqjx91o21/DASH_240, dash_url: https://v.redd.it/yaydjqjx91o21/DASHPlaylist.mpd, duration: 14, hls_url: https://v.redd.it/yaydjqjx91o21/HLSPlaylist.m3u8, is_gif: false, transcoding_status: completed}}
is_reddit_media_domain: true
secure_media_embed: {}
media_only: false
url: https://v.redd.it/yaydjqjx91o21
media: {reddit_video: {fallback_url: https://v.redd.it/yaydjqjx91o21/DASH_1080?source=fallback, height: 1080, width: 540, scrubber_media_url: https://v.redd.it/yaydjqjx91o21/DASH_240, dash_url: https://v.redd.it/yaydjqjx91o21/DASHPlaylist.mpd, duration: 14, hls_url: https://v.redd.it/yaydjqjx91o21/HLSPlaylist.m3u8, is_gif: false, transcoding_status: completed}}
```

**Comment by StefanLobbenmeier** [comment]
Youtube

```
media_embed: {content: &lt;iframe width="600" height="338" src="https://www.youtube.com/embed/coR4Y-DkrLc?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;, width: 600, scrolling: false, height: 338}
secure_media: {type: youtube.com, oembed: {provider_url: https://www.youtube.com/, version: 1.0, title: Pagination in Flutter using Firebase's Cloud Firestore, type: video, thumbnail_width: 480, height: 338, width: 600, html: &lt;iframe width="600" height="338" src="https://www.youtube.com/embed/coR4Y-DkrLc?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;, author_name: Samarth Agarwal, provider_name: YouTube, thumbnail_url: https://i.ytimg.com/vi/coR4Y-DkrLc/hqdefault.jpg, thumbnail_height: 360, author_url: https://www.youtube.com/user/thesamarthagarwal}}
is_reddit_media_domain: false
secure_media_embed: {content: &lt;iframe width="600" height="338" src="https://www.youtube.com/embed/coR4Y-DkrLc?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;, width: 600, scrolling: false, media_domain_url: https://www.redditmedia.com/mediaembed/b4ap7n, height: 338}
media_only: false
url: https://www.youtube.com/watch?v=coR4Y-DkrLc
media: {type: youtube.com, oembed: {provider_url: https://www.youtube.com/, version: 1.0, title: Pagination in Flutter using Firebase's Cloud Firestore, type: video, thumbnail_width: 480, height: 338, width: 600, html: &lt;iframe width="600" height="338" src="https://www.youtube.com/embed/coR4Y-DkrLc?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;, author_name: Samarth Agarwal, provider_name: YouTube, thumbnail_url: https://i.ytimg.com/vi/coR4Y-DkrLc/hqdefault.jpg, thumbnail_height: 360, author_url: https://www.youtube.com/user/thesamarthagarwal}}
```

**Comment by bkonyi** [comment]
> I hope you dont mind if I use this issue to document my findings - I want to gather as many examples of media before thinking about a good design.

Not a problem! Sorry I haven't had more time to work on this myself. Hopefully I can spend some more time on this soon...

**Comment by donovanrost** [comment]
Adding to @StefanLobbenmeier examples of media. This [gfycat](https://www.reddit.com/r/CatastrophicFailure/comments/c0xbh5/in_1984_nasa_and_the_faa_deliberately_crashed_a/.json) example has 

"reddit_video_preview": {
                                "fallback_url": "https://v.redd.it/7fpx9a4xvi431/DASH_360",
                                "height": 360,
                                "width": 640,
                                "scrubber_media_url": "https://v.redd.it/7fpx9a4xvi431/DASH_96",
                                "dash_url": "https://v.redd.it/7fpx9a4xvi431/DASHPlaylist.mpd",
                                "duration": 61,
                                "hls_url": "https://v.redd.it/7fpx9a4xvi431/HLSPlaylist.m3u8",
                                "is_gif": true,
                                "transcoding_status": "completed"
                            },

Which has a link to the video/gif

**Comment by StefanLobbenmeier** [comment]
@donovanrost Thanks for the input :) I actually decided against pursuing this issue further, since I can get away with basically ignoring the fields and only working with the url. I use this library (shameless plug, its my own) to convert them https://github.com/StefanLobbenmeier/video_provider and the mp4 gives me all the metadata I need. Will close for now.
