### ISSUE TITLE
Example of InstalledApp

### ISSUE THREAD

**Issue by guyms** [draw-dev/DRAW#138]
Hello,

Is there anything in the pipeline for installed application workflows/documentation specifically without a secret?

Thanks

**Comment by StefanLobbenmeier** [comment]
Hi :)

It is actually possible, I use it myself. Just set the attributes you don’t
have (I think it is only ClientSecret) to “” and you should be fine.

guyms <notifications@github.com> schrieb am Mi. 10. Apr. 2019 um 06:55:

**Comment by bkonyi** [comment]
I've added documentation to README.md. Let me know if you have more questions!
