### ISSUE TITLE
Add 'best()' to src/listing/mixins/base.dart

### ISSUE THREAD

**Issue by donovanrost** [draw-dev/DRAW#143]
There is subreddit.hot() / .top() / .rising()

.best() doesn't seem to be available, am I missing something?

**Comment by StefanLobbenmeier** [comment]
Hi :) did you find a workaround? Otherwise I will probably try to patch this in a few month, but I am currently quite busy (and so is the actual owner of this repository)

**Comment by bkonyi** [comment]
If it's missing functionality, this shouldn't be too difficult to add. @donovanrost did you find a workaround or was this already implemented somewhere?

**Comment by bkonyi** [comment]
Actually, I'm fairly certain you can just use the `stream` provided by `SubredditRef` as Reddit sorts by 'best' by default as far as I can tell. It might be worth adding a `best()` method either way just for completeness.

**Comment by donovanrost** [comment]
When I opened this issue I didn't realize that on reddit.com, the only subreddit that actually has a 'best' option is 'home' which, I think in DRAW is front. Every other subreddit has a 'hot' ordering which is provided by DRAW. The frontpage api should be the only one with a 'best' option

**Comment by bkonyi** [comment]
> When I opened this issue I didn't realize that on reddit.com, the only subreddit that actually has a 'best' option is 'home' which, I think in DRAW is front. Every other subreddit has a 'hot' ordering which is provided by DRAW. The frontpage api should be the only one with a 'best' option

Right, that's why that was missing... totally forgot about that. You're correct that 'frontpage' is equivalent to 'home'. Anyway, thanks for clearing that up :)
