### ISSUE TITLE
Feature Request: Search for subreddits by name

### ISSUE THREAD

**Issue by dan-rds** [draw-dev/DRAW#146]
I noticed that api_paths.dart contained the mapping for `'search': 'r/{subreddit}/search/',` but I can't find any implementation of this feature.

Can this be done?

**Comment by bkonyi** [comment]
> I noticed that api_paths.dart contained the mapping for `'search': 'r/{subreddit}/search/',` but I can't find any implementation of this feature.
> 
> Can this be done?

Of course!

**Comment by bkonyi** [comment]
Added this functionality as `Subreddits.search` in https://github.com/draw-dev/DRAW/pull/156.
