### ISSUE TITLE
Does restoreAuthenticatedInstance need to be an async action?

### ISSUE THREAD

**Issue by naiveai** [draw-dev/DRAW#147]
It does not appear to actually do anything async - the await it uses is for a function that doesn't actually do any async actions. Am I understanding this wrong? The reason I'm asking it is that it being async causes some difficulty when initializing my application, since I have to wait for it somehow before doing anything. 

EDIT: Looking into this currently, will open a PR for it later, and maybe for some other things that might be useful to installed Flutter apps like mine.

**Comment by bkonyi** [comment]
> It does not appear to actually do anything async - the await it uses is for a function that doesn't actually do any async actions. Am I understanding this wrong? The reason I'm asking it is that it being async causes some difficulty when initializing my application, since I have to wait for it somehow before doing anything.
> 
> EDIT: Looking into this currently, will open a PR for it later, and maybe for some other things that might be useful to installed Flutter apps like mine.

Ah, thanks for pointing that out. This doesn't need to be an `async` method, but it is technically a breaking change as the return type will no longer be a `Future`... I'll have to think about when this change should be made.
