### ISSUE TITLE
More Comments quirk.

### ISSUE THREAD

**Issue by donovanrost** [draw-dev/DRAW#157]
I noticed a weird quirk that probably has more to do with the reddit API than DRAW. But it might be relevant to DRAW

If the parent of a `MoreComments ` is depth 9 -- which I believe is the max depth -- the `count` of that `MoreComments` will be 0, but it is still capable of having children. However the depth of those children will start over at 1 instead of the expected 10.

https://www.reddit.com/r/apolloapp/comments/bllmpu/apollo_for_reddit_app_and_subreddit_faq_do_you/.json

https://www.reddit.com/r/apolloapp/comments/bllmpu/apollo_for_reddit_app_and_subreddit_faq_do_you/emq3omu/.json

Here is an example of a post with a depth 9 comment and then the expanded 'more' with a depth 1 reply

**Comment by StefanLobbenmeier** [comment]
I noticed as well. As far as I know, that is basically the reddit Api telling the Reddit app to display the rest of the comments in a new separate window. You can also notice that the more comments that expands into these „weird“ comments has a count of 0

**Comment by bkonyi** [comment]
Yeah, I'm pretty sure this is just how the Reddit API does things. Has this been causing any issues for you in the context of DRAW or is this just something you've noticed @donovanrost? I know I've run into it while working on `MoreComments` but I was pretty sure everything was working as intended last I checked (it has been awhile though...).

**Comment by donovanrost** [comment]
I was wondering, does it make sense (in the context of DRAW) to handle this case as a separate class since the intent behind `MoreComments` is to get more replies. But this case should be to continue a thread. And since there is unexpected behavior i.e., this case showing 0 comments, when there are actually comments

**Comment by bkonyi** [comment]
> I was wondering, does it make sense (in the context of DRAW) to handle this case as a separate class since the intent behind `MoreComments` is to get more replies. But this case should be to continue a thread. And since there is unexpected behavior i.e., this case showing 0 comments, when there are actually comments

I don't think it would make sense to make this a separate class, simply because `MoreComments` is what Reddit returns for both cases. I've gone ahead and added a couple of properties to `MoreComments` and updated documentation that should make things less confusing.
