### ISSUE TITLE
Error while authorizing: did not contain required parameter "access_token"

### ISSUE THREAD

**Issue by ThatsEli** [draw-dev/DRAW#158]
Hello,

firstly I am relatively new to Flutter so sorry if this is a problem on my side :)

I created a new project and imported the lib. Then I followed the guide on how to setup a ["Installed Application"](https://github.com/draw-dev/DRAW#installed-application-authentication). It works until i call `reddit.auth.authorize(code);`. Then it throws the error 

> FormatException (FormatException: Invalid OAuth response for "https://www.reddit.com/api/v1/access_token": did not contain required parameter "access_token".

and stops working. The Auth code seems to be correct, so I am a bit puzzled about this, maybe there was an update to the Reddit API endpoint and the lib isn't up-to-date anymore. 🤔 I uploaded the project([here](https://github.com/ThatsEli/drawErrorExample)), if you need to try it yourself. (If that implementation seems a bit janky, it is just a early prototype for leaning Flutter/Dart :) )

I hope you can help me to fix this issue and thanks in advance :)

**Comment by StefanLobbenmeier** [comment]
Hi :) I think there are some parameters missing. Let me check my code

**Comment by StefanLobbenmeier** [comment]
```dart
Future<Reddit> login(String state) async {
    Reddit _reddit;
    final userAgent = randomAlphaNumeric(30);

    // Create a `Reddit` instance using a configuration file in the
    // current directory.
    _reddit = Reddit.createWebFlowInstance(
      clientId: clientId,
      clientSecret: "", // Yes, leave it empty
      userAgent: userAgent,
      redirectUri: Uri.parse(redirectUrl),
    );
    //
    //  // Build the URL used for authentication. See `WebAuthenticator`
    //  // documentation for parameters.
    final authUrl = _reddit.auth.url(
      ['*'],
      state,
      compactLogin: true,
    );
    print(authUrl);
    print("state: $state");
    await openLoginPageInBrowser(authUrl.toString());
    return _reddit;
  }
```

**Comment by StefanLobbenmeier** [comment]
This is the Code I Uwe (and just tested). However youre using the newer api and I guess you should keep that. What I missed in your code was the user agent

**Comment by StefanLobbenmeier** [comment]
Actually never mind, that part looks correct. My next guess is that your way of extracting the code did not work, did you check the code with a print?

**Comment by StefanLobbenmeier** [comment]
The other reason I could think of is that the reddit api does not accept foobar as it is not random enough / used by too many people

**Comment by ThatsEli** [comment]
I managed to fix it by using a different useragent as you suggested. Somehow that fixed it, I don't know exactly why that mistake would throw the error I had, but who knows 🤔 Dankeschön für die Hilfe ;) (Thank you for the help!)

**Comment by StefanLobbenmeier** [comment]
@bkonyi should we change this in the Guide? It seems that it was not clear that user_agent needs to be random

**Comment by bkonyi** [comment]
> @bkonyi should we change this in the Guide? It seems that it was not clear that user_agent needs to be random

Thanks for helping @ThatsEli debug @StefanLobbenmeier! I really appreciate your contributions :) 

Yes, we should probably add a commonly asked questions section to the README and cover this there. I'm not certain the user-agent needs to be _random_, but it needs to be something relatively unique (I'm sure `foobar` is used quite frequently, which is likely why @ThatsEli was running into issues. Us programmers are too damn predictable, I guess :-) ).
