### ISSUE TITLE
FormatException: Invalid OAuth response for "https://www.reddit.com/api/v1/access_token": required parameter "error" was not a string, was "401".

### ISSUE THREAD

**Issue by ThatsEli** [draw-dev/DRAW#161]
Hey, it's me again :) So far DRAW works perfectly, but I encountered another bug :( Initial authentication is working perfectly(Using `createInstalledFlowInstance(...)`). Also the restoring of an instance with `restoreAuthenticatedInstance(...)` is working… For about a few hours or so. Before that timefrme everything works. But after that timeframe it throws the following error:

> E/flutter (30955): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid OAuth response for "https://www.reddit.com/api/v1/access_token": required parameter "error" was not a string, was "401".
E/flutter (30955):
E/flutter (30955): {"message": "Unauthorized", "error": 401}
E/flutter (30955): #0      handleAccessTokenResponse 
package:oauth2/src/handle_access_token_response.dart:95
E/flutter (30955): #1      Credentials.refresh 
package:oauth2/src/credentials.dart:230
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #2      Client.refreshCredentials 
package:oauth2/src/client.dart:155
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #3      WebAuthenticator.refresh 
package:draw/src/auth.dart:518
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #4      Authenticator._request 
package:draw/src/auth.dart:189
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #5      Authenticator.get 
package:draw/src/auth.dart:143
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #6      Reddit.get 
package:draw/src/reddit.dart:586
E/flutter (30955): <asynchronous suspension>
E/flutter (30955): #7      User.me 

(I only copied the part of the stacktrace that is about DRAW)
There is no 2FA or something like that enabled on my account, that would remove the authentification from Reddits side(To my knowledge). Maybe I am doing something wrong?

The code for restoring the reddit instance:

> RedditService.reddit = Reddit.restoreAuthenticatedInstance(
>     redditCredentials,
>     clientId: 'yG99FCj-------',
>     userAgent: SettingsService.getKey('redditUserAgent'),
>     redirectUri: Uri.parse('https://thatseliyt.de/')
> );

**Comment by ThatsEli** [comment]
Okay, I just dicovered taking a look at the sourcecode, that the `restoreAuthenticatedInstance(..)` only seems to work with a webFlowInstance. I will try my luck to "fix" it in my fork :)

**Comment by ThatsEli** [comment]
Okay, I should have read the code more indepth: The installedApplicationsInstance is a webFlowInstance without a clientSecret. Then I don't really know where the problem lies 🤔

**Comment by ThatsEli** [comment]
Okay, I think I fixed it. At least for me it works now. It was a really simple fix so I will create a PR is a few minutes. I don't know why this shoould fix my problem that only occurred after a few hours, but who knows 🤷‍♂

**Comment by ThatsEli** [comment]
Opened PR #162

**Comment by bkonyi** [comment]
Thanks for the PR! It almost sounds like your credentials expired and needed to be regenerated, but I'm not completely sure...

**Comment by madqueendany** [comment]
Hello @ThatsEli, @bkonyi, I'm having the same problem... Can you please enlighten me?

**Comment by ThatsEli** [comment]
I hope so :) First of all, are you sure, that the credentials aren't expired? And of what type is your Reddit application(WebFlow, Script or Installed)? If it is installed, it could be that you have the same problem as me and maybe my "fix" should help.

**Comment by madqueendany** [comment]
It's not expired, I was just following the normal flow of authentication so the installed app instance so I might very well be sharing the same problem with you. I also notice that you did a PR for this? How do I implement that?

**Comment by ThatsEli** [comment]
@madqueendany 

Yeah, I created a PR to fix this: When @bkonyi has published the new DRAW version, try to replace `restoreAuthenticatedInstance(...)` with `restoreInstalledAuthenticatedInstance(...)`.

**Comment by madqueendany** [comment]
Thanks guys. I'll be sure to check this out later
