### ISSUE TITLE
Redirect URI parses the string

### ISSUE THREAD

**Issue by madqueendany** [draw-dev/DRAW#163]
my sample `redirect_uri` is `http://localhost:8080`

but when I print the `auth_url`, it prints `http%3A%2F%2Flocalhost%3A8080%2F`

And then when I paste the url to postman, (and remove the *.compact* attribute) I get 

```
you sent an invalid request

— invalid redirect_uri parameter.
```

Then still on postman, when I change it to the unparsed string, i get the correct reponse (the page with **Allow** / **Deny** buttons

**Comment by bkonyi** [comment]
I'm not sure what you mean by `auth_url`; do you mean the `Uri` returned from `reddit.auth.url()`?

You might just need to invoke [Uri.decodeComponent](https://api.dartlang.org/stable/2.4.1/dart-core/Uri/decodeComponent.html) on the string value of the `Uri`.

**Comment by madqueendany** [comment]
Oh I fixed it I think... For the mean time I opted to use a script instance instead of an installed app flow, so now I'm using the package as a read-only instance.

Closing this for now. Thanks!
