### ISSUE TITLE
Reddit no longer provides secret for android apps. How to initialize the Reddit instance?

### ISSUE THREAD

**Issue by manishbeetch** [draw-dev/DRAW#166]

**Comment by ohIcee** [comment]
could you please explain?
I tried with the wiki:
` final reddit = Reddit.createInstalledFlowInstance(userAgent: userAgent,
        configUri: configUri, clientId: "id");`

but after running `final auth_url = reddit.auth.url(['*'], 'foobar');` nothing happens and is null
