### ISSUE TITLE
Search  '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>'

### ISSUE THREAD

**Issue by oliver92** [draw-dev/DRAW#168]
When you try to search a subreddit... example:

<code>await reddit.subreddit("all").search(text, sort: Sort.relevance, params: Map<String, String>()).toList()</code>

The method search cannot be called because it throws:
_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>

I believe its this line thats the cause:
<code>final data = (params != null) ? Map.from(params) : Map();</code>
This alters the map and then when it gets passed to 
<code>ListingGenerator.createBasicGenerator</code>
It throws becuase the map is
<code>Map\<dynamic ,dynamic></code>

I also tried passing null as params parameter but got the same result.

Oliver

**Comment by bkonyi** [comment]
Thanks for filing an issue @oliver92. Would you mind sharing the full stacktrace? This should be relatively simple to fix, but it'd be a huge help if you could provide me with that!

**Comment by oliver92** [comment]
Yes, im sorry for not including it in the first place. here you go:

<code>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>'
#0      SubredditRef.search (package:draw/src/models/subreddit.dart:236:17)
....
</code>

The rest of the stack trace is just my own classes....

Im on version 0.9.0 btw :)

Tnx for the quick response
Oliver

**Comment by bkonyi** [comment]
> Yes, im sorry for not including it in the first place. here you go:
> 
> ` [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap' is not a subtype of type 'Map' #0 SubredditRef.search (package:draw/src/models/subreddit.dart:236:17) `
> The rest of the stack trace is just my own classes....
> 
> Im on version 0.9.0 btw :)
> 
> Tnx for the quick response
> Oliver

Thanks! I've uploaded version 0.9.1 which should hopefully fix this for you. Please let me know if you run into any more issues!

**Comment by oliver92** [comment]
Yup, that solves it. Thank you for the quick response. 

Oliver
