### ISSUE TITLE
Current Authorization flow is HELL

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [draw-dev/DRAW#174]
Sorry for the extremely unprofessional title, but I'm switching over from a self designed API and I'm just running into confusing error after error. Methods that should be required aren't marked as such, there are too many optional parameters that require you to understand the library to decide when to leave out. 
There are too many technical terms that I feel should be abstracted for ease of use.
This is my second time attempting to integrate DRAW into this app. This is more of a feedback issue. If you have some time, please get with me so I can sort out this login flow. Thanks!

Current error AFTER authenticating the user and running `reddit.auth.authorize(code);`:

>       The authorization URL has not yet been generated.

**Comment by ThinkDigitalSoftware** [comment]
Closing as this was more venting than an issue. After going over the instructions one by one, I ended up getting it.

**Comment by bkonyi** [comment]
Yeah, authentication is... weird. Most of the authentication flow, along with the majority of the DRAW API, is inspired by the flow found in PRAW, so if you run into issues in the future you might be able to use PRAW's documentation as a supplementary resource. Glad you figured it out though!

**Comment by ThinkDigitalSoftware** [comment]
Thanks. Can you add required in places where the variable is required or else the method will fail?

**Comment by Bricktheworld** [comment]
Would a more fully explored example help? I have managed to get OAuth working pretty seamlessly with flutter (assuming you are using flutter). Also, I don't think that the confusing convoluted parts of this API are really the fault of this wrapper, it's mostly the fault of Reddit for having all of these roundabout ways of dealing with their API... Like by far Reddit is the worst I've ever seen and this wrapper does a pretty good job about documenting many parts of the OAuth though. What in particular is tripping you up?

**Comment by bkonyi** [comment]
> Thanks. Can you add required in places where the variable is required or else the method will fail?

That's something I can look into doing. Filed #176 to track.

**Comment by ThinkDigitalSoftware** [comment]
Thank you, sir
