### ISSUE TITLE
Quick question, how do I get a post from a given reddit url?

### ISSUE THREAD

**Issue by Bricktheworld** [draw-dev/DRAW#177]
So I need to make a post given a specific url, is this something I have to do myself or is it already built in. I noticed the `Submission.parse()` method with the data prop and I was wondering if I have to manually fetch this from the url adding the .json tag to whatever url and sending an `http.get` request. If so, how would this be done?

Thanks!

**Comment by StefanLobbenmeier** [comment]
You usually get submission from a Listing, for example from a subreddit or the front page. You should not have to construct urls yourself.

If you are looking for a post by id I am not sure how to do that

**Comment by StefanLobbenmeier** [comment]
Could you try: 
https://github.com/draw-dev/DRAW/blob/26a2593cfd7edc2796e7f393d8a0e659e5489d8a/lib/src/models/user_content.dart#L12

**Comment by Bricktheworld** [comment]
@StefanLobbenmeier Yeah for almost all my posts I get it from the front page, however, with this, I am redirecting a link from a web page to my app Reddit app and I need to parse it into a regular submission so I can upvote and whatnot.

Also, I am getting the "abstract class cannot be instantiated" whatever when I do, `UserContent _userContent = UserContent.withPath(reddit, url);`. So how should i properly do this?

**Comment by Bricktheworld** [comment]
@StefanLobbenmeier Actually yes this works!!! Thank you so much!

And for anyone in the future who has this issue, here is how I solved it:

`SubmissionRef submissionRef = SubmissionRef.withPath(reddit, link);
Submission submission = await submissionRef.populate();`
