### ISSUE TITLE
Requesting a null safe release

### ISSUE THREAD

**Issue by MrFrankenstein** [draw-dev/DRAW#189]
I have checked the dependencies and of them only "ini" package is not null safe (its null safe version is still a beta release).

**Comment by bkonyi** [comment]
Yup, this is on my radar. Hopefully I'll have something by EOD Thursday.

**Comment by bkonyi** [comment]
@MrFrankenstein  you can `pubspec.yaml` to include `draw: ^1.0.0` for the latest null-safe version. Please file issues if you run into any problems!
