### ISSUE TITLE
Cannot create Reddit.createUntrustedReadOnlyInstance()

### ISSUE THREAD

**Issue by MrFrankenstein** [draw-dev/DRAW#195]
Getting the following exception when trying to create reddit untrusted instance.

`Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>?' in type cast`

Please help.

**Comment by bkonyi** [comment]
@MrFrankenstein can you please provide a stack trace?

**Comment by MrFrankenstein** [comment]
@bkonyi here's the stack trace

`E/flutter ( 5466): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>?' in type cast
E/flutter ( 5466): #0      Authenticator._requestTokenUntrusted (package:draw/src/auth.dart:280:26)
E/flutter ( 5466): #1      ReadOnlyAuthenticator._authenticationFlow (package:draw/src/auth.dart:394:13)
E/flutter ( 5466): #2      ReadOnlyAuthenticator.createUntrusted (package:draw/src/auth.dart:380:25)
E/flutter ( 5466): #3      new Reddit._untrustedReadOnlyInstance (package:draw/src/reddit.dart:449:27)
E/flutter ( 5466): #4      Reddit.createUntrustedReadOnlyInstance (package:draw/src/reddit.dart:119:27)
E/flutter ( 5466): #5      BrowseFlow.startBrowseFlow (package:re_red/browse_flow.dart:26:40)
E/flutter ( 5466): #6      LandingPage.build.<anonymous closure> (package:re_red/landing_page.dart:47:56)
E/flutter ( 5466): #7      LandingPage.build.<anonymous closure> (package:re_red/landing_page.dart:46:36)
E/flutter ( 5466): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
E/flutter ( 5466): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5466): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter ( 5466): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 5466): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter ( 5466): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 5466): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter ( 5466): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter ( 5466): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter ( 5466): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter ( 5466): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter ( 5466): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter ( 5466): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter ( 5466): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter ( 5466): #22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter ( 5466): #23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter ( 5466): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter ( 5466): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter ( 5466): #26     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter ( 5466): #27     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 5466): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter ( 5466): #29     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter ( 5466): #30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter ( 5466): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)`

**Comment by MrFrankenstein** [comment]
@bkonyi here's the stack trace

> E/flutter ( 5466): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>?' in type cast
> E/flutter ( 5466): #0      Authenticator._requestTokenUntrusted (package:draw/src/auth.dart:280:26)
> E/flutter ( 5466): #1      ReadOnlyAuthenticator._authenticationFlow (package:draw/src/auth.dart:394:13)
> E/flutter ( 5466): #2      ReadOnlyAuthenticator.createUntrusted (package:draw/src/auth.dart:380:25)
> E/flutter ( 5466): #3      new Reddit._untrustedReadOnlyInstance (package:draw/src/reddit.dart:449:27)
> E/flutter ( 5466): #4      Reddit.createUntrustedReadOnlyInstance (package:draw/src/reddit.dart:119:27)
> E/flutter ( 5466): #5      BrowseFlow.startBrowseFlow (package:re_red/browse_flow.dart:26:40)
> E/flutter ( 5466): #6      LandingPage.build.<anonymous closure> (package:re_red/landing_page.dart:47:56)
> E/flutter ( 5466): #7      LandingPage.build.<anonymous closure> (package:re_red/landing_page.dart:46:36)
> E/flutter ( 5466): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
> E/flutter ( 5466): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> E/flutter ( 5466): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
> E/flutter ( 5466): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
> E/flutter ( 5466): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
> E/flutter ( 5466): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
> E/flutter ( 5466): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
> E/flutter ( 5466): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
> E/flutter ( 5466): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
> E/flutter ( 5466): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
> E/flutter ( 5466): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
> E/flutter ( 5466): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
> E/flutter ( 5466): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
> E/flutter ( 5466): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
> E/flutter ( 5466): #22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
> E/flutter ( 5466): #23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
> E/flutter ( 5466): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
> E/flutter ( 5466): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
> E/flutter ( 5466): #26     _rootRunUnary (dart:async/zone.dart:1370:13)
> E/flutter ( 5466): #27     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
> E/flutter ( 5466): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
> E/flutter ( 5466): #29     _invoke1 (dart:ui/hooks.dart:182:10)
> E/flutter ( 5466): #30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
> E/flutter ( 5466): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

**Comment by MrFrankenstein** [comment]
Hi @bkonyi 
Just a gentle remainder to ask if you had a chance to look at this issue.

**Comment by tjarvstrand** [comment]
Hi! I just hit the same issue. Is a solution for this on the horizon?
