### ISSUE TITLE
Subreddit Submit Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>' in type cast

### ISSUE THREAD

**Issue by abhishekove** [draw-dev/DRAW#203]
Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>' in type cast. The error is caused when I try to use submit from subreddit to post some data on that subreddit.

**Comment by abhishekove** [comment]
E/flutter (11805): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>' in type cast
E/flutter (11805): #0      Authenticator._request
package:draw/src/auth.dart:192
E/flutter (11805): #1      Authenticator.post
package:draw/src/auth.dart:147
E/flutter (11805): #2      Reddit.post
package:draw/src/reddit.dart:638
E/flutter (11805): #3      SubredditRef.submit.<anonymous closure>
package:draw/…/models/subreddit.dart:308
E/flutter (11805): #4      SubredditRef.submit.<anonymous closure>
package:draw/…/models/subreddit.dart:308
E/flutter (11805): #5      SubredditRef._throwOnInvalidSubreddit
package:draw/…/models/subreddit.dart:70

Complete error

**Comment by SupremeDeity** [comment]
#202 Most likely fixes this. Waiting on a someone to merge it.

**Comment by abhishekove** [comment]
Thanks, @SupremeDeity. It works for me now. The pull request must be merged.

**Comment by bkonyi** [comment]
Thanks for being patient everyone! I've been quite busy with travel and haven't had much time to review issues/PRs. I've merged the above change, will probably publish a new version today.
