### ISSUE TITLE
how to get subreddit icon like in PRAW

### ISSUE THREAD

**Issue by xBLACKICEx** [draw-dev/DRAW#218]
in PRAW:
```python
sub = reddit.subreddit("redditdev")
print(sub.icon_img)
```
how to this with draw.
thanks for help.

**Comment by MrFrankenstein** [comment]
I don't think there is. I just parse the json object from 'https://www.reddit.com/api/info.json?sr_name=' and get the icon URL from it. Let me know if you find something simpler.

**Comment by bkonyi** [comment]
Wow, totally missed this one... sorry about that! I think you're looking for [`iconImage'` on the `Subreddit` class](https://pub.dev/documentation/draw/latest/draw/Subreddit/iconImage.html).
