### ISSUE TITLE
Invalid OAuth response for "https://www.reddit.com/api/v1/access_token": required parameter "error" was not a string, was "400".

### ISSUE THREAD

**Issue by Lilja** [draw-dev/DRAW#226]
I previously changed my 2FA setup for my reddit account and then tested to use the API. I guess there is some part of the code that is validating the http-response when getting an access token from reddit. I'm trying my hardest to find where, but have a hard time where this code actually lives.

Willing to send a PR, just can't find where to look.

**Comment by bkonyi** [comment]
Do you have a stack trace by any chance?

**Comment by Lilja** [comment]
@bkonyi I did some late night research and found out that it's probably done by the dart oauth lib. 

[See this link](https://github.com/dart-lang/oauth2/blob/4172ae54c85753ae01fdb4b35527eccc02afa673/lib/src/handle_access_token_response.dart#L140), there's just too much of the exception message that is similar to the code to not be related.

I'm using `Reddit.createInstalledFlowInstance` which is creating `AuthorizationCodeGrant`([multiple times, here](https://github.com/draw-dev/DRAW/blob/0a4cfbc402df8d2fb4a4d7ae994d67e1ecc25733/lib/src/reddit.dart)). Can't find the trail between that class and the method I copied earlier. But it's likely it's related somehow!

I guess the core issue is that reddit doesn't fully implement the oauth2 spec by not returning the proper expected return format of that specific method. But I don't know how much time and energy it's worth trying to chase down reddit devs and letting them know they are not fully oauth2 compliant?...

**Comment by Lilja** [comment]
Stack trace:
```
E/flutter (27971): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid OAuth response for "https://www.reddit.com/api/v1/access_token": required parameter "error" was not a string, was "400".
E/flutter (27971):
E/flutter (27971): {"message": "Bad Request", "error": 400}
E/flutter (27971): #0      handleAccessTokenResponse
handle_access_token_response.dart:109
E/flutter (27971): #1      Credentials.refresh
credentials.dart:253
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #2      Client.refreshCredentials
client.dart:169
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #3      WebAuthenticator.refresh
auth.dart:490
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #4      Authenticator._request
auth.dart:180
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #5      Reddit.get
reddit.dart:624
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #6      User.me
user.dart:53
E/flutter (27971): <asynchronous suspension>
E/flutter (27971): #7      testAuth
auth.dart:194
E/flutter (27971): <asynchronous suspension>
```

**Comment by SupremeDeity** [comment]
Reddit response indeed does not follow the OAuth specs for error response. Also its not just a slight mistake. The name for the error description parameter is also wrong. Heck the error parameter is supposed to return something like `invalid_request` and not 400 or "400".

Its all messed up. However fortunately we shouldn't need to mess with this as we somehow infer that the bad request is a `invalid_request` error. Reference: [OAuth specs RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).

So just ignore this and check if the request you are making has invalid parameters. If its not happening from your side then check the request that DRAW is making is correct or not.

**Comment by Lilja** [comment]
Yes you are correct @SupremeDeity. I've reported the issue to reddit and they seem not too interested in reach out back or fixing it.

Besides, working on the reddit API seems to risky given the state of reddit as of now. I've moved on to different projects.
