### ISSUE TITLE
submit media

### ISSUE THREAD

**Issue by ethicnology** [draw-dev/DRAW#229]
Hey fellows,

I wonder if there is a way to do [submit_image](https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html#praw.models.Subreddit.submit_image), [submit_video](https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html#praw.models.Subreddit.submit_video) with DRAW library and if so, do you have a link to an example ?

Thank you for your work

**Comment by SupremeDeity** [comment]
From what i can see from the subreddit model, no. It only provides a `submit()` method which you can use to submit text posts with inline media.

If you really want to, you can take a look at the Reddit API specs and how PRAW implements that specific methods and recreate the method in DRAW's subreddit model. It shouldn't be that hard.

If you do decide to implement it yourself. Send a PR here :)

**Comment by ethicnology** [comment]
Is there a list of the covered/uncovered endpoints ?

**Comment by SupremeDeity** [comment]
> Is there a list of the covered/uncovered endpoints ?

The ones covered by `DRAW`? Not to my knowledge. The endpoints for reddit api can be found on the internet on their official api docs.

Also I'm not sure if `DRAW` is being actively developed any longer. The main guy is either busy or has abandoned this.

**Comment by ethicnology** [comment]
Thank you for your answers
