### ISSUE TITLE
"OS not Recognized by Draw" thrown when attempting to run on Android

### ISSUE THREAD

**Issue by PiwwowPants** [draw-dev/DRAW#38]
In the config_file_reader._getUserConfigPath() method, a check occurs for macOS, Linus, and Windows. When run on Android (and presumably iOS), all checks will fail and it will fall through to throwing an error.
This makes usage with Flutter a non-option.

Additional checks should be added for Platform.isAndroid and Platform.isIOS

**Comment by bkonyi** [comment]
Thanks for the report @PiwwowPants, I'll look into this ASAP!

**Comment by bkonyi** [comment]
@PiwwowPants, I've landed a workaround for this. If you're not planning on using a `draw.ini`, you should be able to authenticate properly now using `Reddit.createInstance` using your credentials there.
