### ISSUE TITLE
No way to restore saved credentials when using WebAuthenticator flow

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#47]
How can I save the current accessToken (or the refreshToken) when the user closes the app, and reuse it the next time the user opens the app without going again through the authentication browser where the user needs to insert the username and password?

**Comment by bkonyi** [comment]
You should be able to get the OAuth2 credentials from the `Authenticator`'s `credentials` [property](https://pub.dartlang.org/documentation/draw/0.1.3/draw/Authenticator/credentials.html). To save, you should be able to do something like this [example](https://pub.dartlang.org/documentation/oauth2/1.2.0/), but there currently isn't a way to repopulate them through DRAW's API (a major oversight of mine). I'll add a way to do that this weekend.

**Comment by bkonyi** [comment]
This should be resolved once #52 is merged.

**Comment by bkonyi** [comment]
Fix is available in version 0.1.5
