### ISSUE TITLE
Reddit class doesn't have comment attribute

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#60]
To get a post by id I do:
```
Reddit reddit;
...
reddit.submission(id: postId).populate().then((s) => s.upvote());
```
But there doesn't seem to be a way to do this for a comment.

**Comment by bkonyi** [comment]
You're correct, that's not implemented yet. I'll do this tonight.

**Comment by bkonyi** [comment]
Looks like this is a bit more involved than I thought. I'll get to this sometime tomorrow.
