### ISSUE TITLE
Ability to login as Installed Application OAuth2?

### ISSUE THREAD

**Issue by KirkBushman** [draw-dev/DRAW#68]
Hi, I've taken a look at the lib and it looks like you can only use it as WebApp or ScriptApp.

I wish to use it in Flutter: is there a plan to add a new method of login that uses UUID and not a secret? or is this lib pure dart only? 

Thanks in advance for the answer.

**Comment by bkonyi** [comment]
Hi @KirkBushman! Thanks for the question.

For Flutter, you'll want to use the WebAuthenticator flow described in the README as this allows for a user to authenticate via a Reddit login page and accept the permissions requested by your application. After the user accepts the permissions requested, a token is provided in the redirect URL which then needs to be passed back to Reddit to obtain an OAuth token. This is very similar to what [PRAW does](http://praw.readthedocs.io/en/latest/getting_started/authentication.html#web-application).

Hope that helps!

**Comment by Murtaza0xFF** [comment]
How do you go about capturing the code from the redirect URL?
