### ISSUE TITLE
Application Only Oauth

### ISSUE THREAD

**Issue by Ivaskuu** [draw-dev/DRAW#84]
Hi,

I would like to know if Draw supports Application Only Oauth, which seems to be browsing Reddit without logging in, providing read-only scopes.

Link for reference: https://github.com/reddit-archive/reddit/wiki/OAuth2#application-only-oauth  

Thanks :grin:

**Comment by hundeva** [comment]
Agreed, providing a default view without logging in a user would help a lot in terms of UX!

**Comment by bkonyi** [comment]
I'll add this shortly. Sorry for the delay so far! I'll try to get something out this week but will for sure have this done by mid next week.

**Comment by hundeva** [comment]
No worries, I just started to play around with the idea of a reddit client written in Flutter. Thought it would be an awesome learning project, I can just force a login for a while anyway!

**Comment by bkonyi** [comment]
Awesome! I plan on doing some Flutter development for Reddit as well eventually, but I need to finish up the majority of the work on DRAW first. I've been unfortunately busy with work, so I haven't had a chance to finish things up. Soon though!

**Comment by bkonyi** [comment]
Sorry for the delays. Was pretty burnt out and needed some time away from the screen.

PR #83 has the change for application only OAuth, both trusted and untrusted.

**Comment by bkonyi** [comment]
This is now resolved in DRAW version 0.3.3. Update your `pubspec.yaml` and run `pub get` to get the latest version!
