### ISSUE TITLE
No support for preview attribute of submission

### ISSUE THREAD

**Issue by Heasummn** [draw-dev/DRAW#99]
At the moment there is no support for the preview attribute of a submission. This doesn't seem like it would be too difficult to implement as it is similar to the thumbnail.

**Comment by bkonyi** [comment]
Thanks for the suggestion @Heasummn! I'll take a look and get that added for you.

In the meantime, I'm fairly certain you should be able to pull this value out of the `data` property for the submission (although I'm not certain which key it would be under).

**Comment by TheNightmanCodeth** [comment]
I'm accessing the preview property like so:
`post.data["preview"]["images"][0]["source"]["url"]`
just swap out the `0` for the resolution you want. 0 is full resolution, up to (i think) 4 which is the smallest size. However, the preview property is sometimes not available. Some subreddits can choose to have the feature disabled by default so if you're using an unauthorized client, or your user doesn't have a certain setting enabled on their profile an exception will be thrown.

**Comment by bkonyi** [comment]
Sorry for the delay on this. I've published version 0.4.0 which includes a `preview` property in `Submission`. It looks like the Dart 2.0 release broke a couple of dependencies that haven't updated their SDK constraints, so it looks like `dartdoc` won't generate the documentation. Take a look [here](https://github.com/draw-dev/DRAW/blob/master/lib/src/models/submission_impl.dart#L205) for the signature.
